/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Game */

#ifndef _Included_Game
#define _Included_Game
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Game
 * Method:    getBoard
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_Game_getBoard
  (JNIEnv *, jobject);

/*
 * Class:     Game
 * Method:    makeMovement
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_Game_makeMovement
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     Game
 * Method:    gameOver
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Game_gameOver
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
